Fix compilation error: Use FILE_TYPE_NONE instead of MENU_SETTINGS_INFO
The constant MENU_SETTINGS_INFO does not exist. Info-type menu entries
should use FILE_TYPE_NONE, as seen in other non-interactive displays
throughout the menu system.